/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnyType } from './anyType';

export interface ReportState { 
    reportStateId?: number;
    reportStateName?: string;
    reportStateState?: number;
    reportStateDeleted?: AnyType;
    reportId?: number;
    reportStateDateFile?: Date;
    reportStateLastMod?: Date;
    reportStateModNotes?: string;
    reportStateType?: number;
    reportStateAttachedFileName?: string;
}