/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnyType } from './anyType';

export interface Report { 
    reportId?: number;
    reportName?: string;
    reportDescription?: string;
    periodicityId?: number;
    reportFirstDate?: Date;
    reportNextDate?: Date;
    reportDateCell?: string;
    reportExcelFileName?: string;
    centralId?: number;
    reportAdminNote?: string;
    reportValidationRequired?: string;
    reportOpRange?: string;
    reportExecHour?: number;
    mailListId?: number;
    reportNextUtcDate?: Date;
    userId?: number;
    reportFileNameFormat?: string;
    reportAttachedFileNameFormat?: string;
    reportUserGroupId?: number;
    revisionMailListId?: number;
    reportPostExecutionExcelMacro?: string;
    reportPreExecutionExcelMacro?: string;
    reportDeleted?: AnyType;
}